#!/bin/bash
set -e

docker run -dit \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /opt/vent_files:/opt/vent_files \
           -v $(pwd)/.plugin_config.yml:/root/.plugin_config.yml \
           -v $(pwd)/.vent_startup.yml:/root/.vent_startup.yml \
           -e controller_uri=$controller_uri \
           -e controller_user=$controller_user \
           -e controller_pass=$controller_pass \
           -e controller_type=$controller_type \
           -e controller_log_file=$controller_log_file \
           -e controller_config_file=$controller_config_file \
           -e collector_nic=$collector_nic \
           -e controller_mirror_ports="$controller_mirror_ports" \
           -e rabbit_enabled=$rabbit_enabled \
           -e FA_RABBIT_ENABLED=$FA_RABBIT_ENABLED \
           -e FA_RABBIT_HOST=$FA_RABBIT_HOST \
           -e FA_RABBIT_EXCHANGE=$FA_RABBIT_EXCHANGE \
           -e FA_RABBIT_ROUTING_KEY=$FA_RABBIT_ROUTING_KEY \
           -e FA_RABBIT_PORT=$FA_RABBIT_PORT \
           -e max_concurrent_reinvestigations=$max_concurrent_reinvestigations \
           --name vent \
           cyberreboot/vent

echo -n "waiting for required containers to build and start (this might take a little while)..."
until [ "$(docker ps -q -f name=cyberreboot-vent-syslog-master)" ] && [ "$(docker container inspect -f {{.State.Running}} cyberreboot-vent-syslog-master)" = "true" ]
do
	echo -n "\\"
	echo -en "\b"
	sleep 0.3
	echo -n "|"
	echo -en "\b"
	sleep 0.3
	echo -n "/"
	echo -en "\b"
	sleep 0.3
	echo -n "-"
	echo -en "\b"
	sleep 0.3
done

echo "done."

docker logs -f cyberreboot-vent-syslog-master

