https://github.com/cyberreboot/vent:
    file_drop:
        branch: v0.9.8
        build: yes
        start: yes
    network_tap:
        branch: v0.9.8
        build: yes
        start: yes
    rabbitmq:
        branch: v0.9.8
        build: yes
        start: yes
    redis:
        branch: v0.9.8
        build: yes
        start: yes
    rq_dashboard:
        branch: v0.9.8
        build: yes
        start: yes
    rq_worker:
        branch: v0.9.8
        build: yes
        start: yes
        settings:
            instances: 4
    syslog:
        branch: v0.9.8
        build: yes
        start: yes
https://github.com/cyberreboot/poseidon:
    '@':
        branch: v0.6.7
        build: yes
        start: yes
    api:
        branch: v0.6.7
        build: yes
        start: yes
https://github.com/cyberreboot/vent-plugins:
    pcap_to_node_pcap:
        branch: v0.1.3
        build: yes
    p0f:
        branch: v0.1.3
        build: yes
    tcprewrite_dot1q:
        branch: v0.1.3
        build: yes
https://github.com/cyberreboot/crviz:
    '@':
        branch: v0.3.9
        build: yes
        start: yes
https://github.com/cyberreboot/networkml:
    '@':
        branch: v0.3.6
        build: yes
vent.cfg:
    build-options:
        use_existing_images: yes
