FROM jupyter/notebook
MAINTAINER dgrossman <dgrossman@iqt.org>

ADD . /poseidonJupyter
WORKDIR /poseidonJupyter

# install dependencies of plugins for poseidon
RUN for file in $(find poseidon/* -name "requirements.txt"); \
    do \
        pip install -r $file; \
    done
