#!/bin/bash
set -e

default_iface=$(ip route list | head -1 | awk '{print $5}')
default_ip=$(ip addr show dev "$default_iface" | awk '$1 == "inet" { sub("/.*", "", $2); print $2 }' | head -1)

# get grafana json files
if [[ -z "${FAUCET_PREFIX}" ]]; then
    # clone faucet
    cd /opt && git clone https://github.com/faucetsdn/faucet

    # copy over compose and prometheus files
    cp docker-compose.yaml /opt/faucet/docker-compose.yaml
    cp prometheus-docker-compose.yml /opt/faucet/etc/prometheus/prometheus-docker-compose.yml

    # ensure gauge config is there
    cp gauge.yaml /etc/faucet/gauge.yaml

    # copy over dashboards for grafana
    cp dashboards.yaml /opt/grafana/provisioning/dashboards/dashboards.yaml
    cp ../../docs/poseidon_stats.json /opt/grafana/dashboards/poseidon_stats.json
    curl -K https://docs.faucet.nz/en/latest/_static/grafana-dashboards/faucet_instrumentation.json -o /opt/grafana/dashboards/faucet_instrumentation.json
    curl -K https://docs.faucet.nz/en/latest/_static/grafana-dashboards/faucet_inventory.json -o /opt/grafana/dashboards/faucet_inventory.json
    curl -K https://docs.faucet.nz/en/latest/_static/grafana-dashboards/faucet_port_statistics.json -o /opt/grafana/dashboards/faucet_port_statistics.json

    cd /opt/faucet && FAUCET_EVENT_SOCK=1 FAUCET_CONFIG_STAT_RELOAD=1 FA_RABBIT_HOST=$default_ip docker-compose -f docker-compose.yaml -f adapters/vendors/rabbitmq/docker-compose.yaml up --build -d && popd
    poseidon restart
fi
