#!/bin/bash
set -e

default_iface=$(ip route list | head -1 | awk '{print $5}')
default_ip=$(ip addr show dev "$default_iface" | awk '$1 == "inet" { sub("/.*", "", $2); print $2 }' | head -1)

# get grafana json files
if [[ -z "${FAUCET_PREFIX}" ]]; then
    # clone faucet
    rm -rf /opt/faucet
    rm -rf /opt/grafana
    pushd `pwd` && cd /opt; git clone https://github.com/faucetsdn/faucet; popd

    # copy over compose and prometheus files
    cp docker-compose.yaml /opt/faucet/docker-compose.yaml
    cp prometheus-docker-compose.yml /opt/faucet/etc/prometheus/prometheus-docker-compose.yml

    # ensure gauge config is there
    mkdir -p /etc/faucet
    cp gauge.yaml /etc/faucet/gauge.yaml

    # copy over dashboards for grafana
    mkdir -p /opt/grafana/provisioning/dashboards
    mkdir -p /opt/grafana/dashboards
    cp dashboards.yaml /opt/grafana/provisioning/dashboards/dashboards.yaml
    cp ../../docs/poseidon_stats.json /opt/grafana/dashboards/poseidon_stats.json
    wget -O /opt/grafana/dashboards/faucet_instrumentation.json https://docs.faucet.nz/en/latest/_static/grafana-dashboards/faucet_instrumentation.json
    wget -O /opt/grafana/dashboards/faucet_inventory.json https://docs.faucet.nz/en/latest/_static/grafana-dashboards/faucet_inventory.json
    wget -O /opt/grafana/dashboards/faucet_port_statistics.json https://docs.faucet.nz/en/latest/_static/grafana-dashboards/faucet_port_statistics.json

    pushd `pwd` && cd /opt/faucet; docker-compose down; FAUCET_EVENT_SOCK=1 FAUCET_CONFIG_STAT_RELOAD=1 FAUCET_CONFIG_AUTO_REVERT=1 FA_RABBIT_HOST=$default_ip docker-compose -f docker-compose.yaml -f adapters/vendors/rabbitmq/docker-compose.yaml up --build -d; popd
    rm -rf /opt/vent_files/.vent/vent.init
    poseidon restart
    wget -O- --auth-no-challenge --post-data='{"name":"${DS_PROMETHEUS}","type":"prometheus","access":"proxy","url":"http://prometheus:9090","basicAuth":false,"isDefault":true}' --header="Content-Type: application/json;charset=UTF-8charset=UTF-8" 'http://admin:admin@0.0.0.0:3000/api/datasources'

fi
